---
- name: Install evengsdk via pip
  pip:
    name: eve-ng
    state: present
  delegate_to: localhost

- name: Check if platform-version is being already installed in eve-ng
  eveng_fetch:
    host: "{{ inventory_hostname }}"
    username: "{{ eveng_username }}"
    password: "{{ eveng_admin_pass }}"
    nodes: "{{ eveng.nodes }}"
  register: out_images_presence
  no_log: true
  delegate_to: localhost

- name: Check if platform-version is supported
  ansible.builtin.assert:
    that: "{{ download_links[node['platform_version']] is defined }}"
  loop: "{{ out_images_presence.nodes }}"
  loop_control:
    label: "{{ node.platform_version }}"
    loop_var: node

- name: Install missing images
  ansible.builtin.include_tasks: "platforms/{{ missing_images['platform'] }}/install.yml"
  loop: "{{ out_images_presence.nodes | selectattr('firmware_present', 'equalto', false) | unique }}"
  loop_control:
    loop_var: missing_images
