---
- name: Configure EVE-NG
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
  - name: Download 
    ansible.builtin.get_url:
      url: https://ash-speed.hetzner.com/100MB.bin
      dest: /tmp
    delegate_to: localhost
    async: 1000
    poll: 0
    register: yum_sleeper


  - name: Check on an async task
    async_status:
      jid: "{{ yum_sleeper.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 10
    delegate_to: localhost
