---
- name: Install EVE-NG
  hosts: all
  gather_facts: false
  become: true

  tasks:
    # - name: Call install role
    #   include_role:
    #     name: install_eveng

    # - name: Call change eveng password role
    #   include_role:
    #     name: eveng_change_password
