---
download_links:
  isrv-17.02.02: https://labhub.eu.org/api/raw/?path=/UNETLAB%20II/addons/qemu/Cisco%20ISRv/isrv-17.02.02.tgz
  isrv-17.03.03: https://labhub.eu.org/api/raw/?path=/UNETLAB%20II/addons/qemu/Cisco%20ISRv/isrv-universalk9.17.03.03.tgz
  isrv-17.01.01: https://drive.google.com/uc?export=download&id=1IV_cYG8ysxQ_7EtwvOehaIeZnMbWHJ7L
