---
name: Ansible EVE-NG

on:
  push:
    paths:
      - 'ans-app-eveng/**'
      - 'ans_eveng_iac.yml'
      - '.github/workflows/ans-eveng-iac.yml'
  pull_request:
    paths:
      - 'ans-app-eveng/**'
      - 'ans_eveng_iac.yml'
      - '.github/workflows/ans-eveng-iac.yml'

jobs:

  # ansible-lint:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     # - name: Set up Python
  #     #   uses: actions/setup-python@v3
  #     #   with:
  #     #     python-version: '3.x'

  #     # - name: Install Ansible Lint
  #     #   run: |
  #     #     python -m pip install --upgrade pip
  #     #     pip install ansible-lint

  #     # - name: Run Ansible Lint
  #     #   run: ansible-lint

  #     - name: Run ansible-lint
  #       uses: ansible/ansible-lint@main
  #       with:
  #         # args: ""
  #         setup_python: "true"
  #         working_directory: "./ans-app-eveng"
  #         # requirements_file: ""

  ansible-install-eveng:
    runs-on: ubuntu-latest
    # needs: ansible-lint
    defaults:
      run:
        working-directory: "ans-app-eveng"
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          pip install pyyaml
          python -m pip show pyyaml

      - name: Install Ansible
        run: |
          sudo apt install -y ansible
          ansible --version

      - name: Install EVE-NG Ansible playbook
        run: |
          chmod +x ./inventory/dynamic_iac_inventory.py
          ansible-playbook -i ./inventory/dynamic_iac_inventory.py install-eveng.yml
